spring.application.name=template
#logging.level.root=debug

spring.web.resources.static-locations=classpath:/static/,file:uploads/

app.frontend.url=http://localhost:3000
app.max-failed-password-attempts=3
app.password.bcrypt.strength=12
app.security.tokenDurationInHours=12
app.security.jwt-secret=${JWT_SECRET}
app.password.reset.token.expiry-minutes=15
app.password.reset.request.min-duration-ms=1000
upload.directory=uploads/users
oauth.code.ttl-s=30

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# --- Datasource (PostgreSQL) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true

# --- Flyway ---
spring.flyway.enabled=true

# --- Flyway Debugging ---
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
#logging.level.org.flywaydb=DEBUG

# ======================
# GOOGLE
# ======================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ======================
# MAIL
# ======================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=no-reply@easyevent-app.com